version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save 20 1
      --loglevel warning
      --requirepass ${REDIS_PASSWORD:-your_redis_password}
    volumes:
      - redis_data:/data
    networks:
      - monitoring

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: unless-stopped
    command:
      - "--redis.addr=redis:6379"
      - "--redis.password=${REDIS_PASSWORD:-your_redis_password}"
    ports:
      - "9121:9121"
    networks:
      - monitoring

volumes:
  redis_data:
    driver: local

networks:
  monitoring:
    driver: bridge